using FluentValidation;
using AgriculturalMonitorSystem.Src.Features.Sensor.Models.DTOs;

namespace AgriculturalMonitorSystem.Src.Features.Sensor.Validators;

// Readings are generated by the simulation service, not manually submitted.
// This validator is reserved for future manual reading input if needed.
public class SensorReadingValidator : AbstractValidator<SensorReadingDto>
{
    public SensorReadingValidator()
    {
        RuleFor(x => x.SensorId).NotEmpty().WithMessage("Sensor ID is required.");
        RuleFor(x => x.FarmId).NotEmpty().WithMessage("Farm ID is required.");
    }
}
